# Name of the application
spring.application.name=renova-sangue

#JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true


# profile
spring.profiles.active=postgres
